(function() {var implementors = {};
implementors["actix_web"] = ["impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/client/struct.ClientResponse.html\" title=\"struct actix_web::client::ClientResponse\">ClientResponse</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/ws/struct.WsClientReader.html\" title=\"struct actix_web::ws::WsClientReader\">WsClientReader</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/ws/struct.WsStream.html\" title=\"struct actix_web::ws::WsStream\">WsStream</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/multipart/struct.Multipart.html\" title=\"struct actix_web::multipart::Multipart\">Multipart</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/multipart/struct.Field.html\" title=\"struct actix_web::multipart::Field\">Field</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/payload/struct.Payload.html\" title=\"struct actix_web::payload::Payload\">Payload</a>","impl <a class=\"trait\" href=\"https://docs.rs/futures/0.1/futures/stream/trait.Stream.html\" title=\"trait futures::stream::Stream\">Stream</a> for <a class=\"struct\" href=\"actix_web/payload/struct.ReadAny.html\" title=\"struct actix_web::payload::ReadAny\">ReadAny</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
